<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Robin Barnett-Wake (Comptroller of Maryland Information Technology Division) -->
<xsd:schema xmlns="http://www.irs.gov/efile" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.irs.gov/efile" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:annotation>
		<xsd:documentation>
			<Description>Estandards version of IRS Form 1099B</Description>
			<TaxYear>2022</TaxYear>
			<ReleaseDate>July 12, 2022</ReleaseDate>
		</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="../../Common/efileTypes.xsd"/>
	<xsd:include schemaLocation="../../Common/StateeFileTypes.xsd"/>
	<xsd:include schemaLocation="../IndividualStateEnumerations.xsd"/>
	<xsd:element name="State1099B">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="State1099BType">
					<xsd:attributeGroup ref="DocumentAttributes">
						<xsd:annotation>
							<xsd:documentation>Common return document attributes</xsd:documentation>
						</xsd:annotation>
					</xsd:attributeGroup>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="State1099BType">
		<xsd:sequence>
			<!-- Corrected Indicator -->
			<xsd:element name="CorrectedInd" type="CheckboxType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Corrected Indicator</Description>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<!-- Void Indicator -->
			<xsd:element name="VoidInd" type="CheckboxType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Void Indicator</Description>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<!-- Payer Name -->
			<xsd:element name="PayerName">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Payer name</Description>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="BusinessNameType">
							<xsd:attribute name="payerNameControl" type="BusinessNameControlType" use="required"/>
						</xsd:extension>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
			<!-- Payer Address -->
			<xsd:choice minOccurs="0">
				<!-- Payer US Address -->
				<xsd:element name="PayerUSAddress" type="USAddressType">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Payer US address</Description>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<!-- Employer Foreign Address -->
				<xsd:element name="PayerForeignAddress" type="ForeignAddressType">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Payer foreign address</Description>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<!-- Payer Phone Number -->
			<xsd:choice minOccurs="0">
				<xsd:element name="PayerPhone" type="PhoneNumberType"/>
				<xsd:element name="PayerForeignPhone" type="ForeignPhoneNumberType"/>
			</xsd:choice>
			<!-- Payer EIN -->
			<xsd:element name="PayerEIN" type="EINType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Payer Identification Number</Description>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice>
				<xsd:element name="IndividualRecipient">
					<xsd:complexType>
						<xsd:sequence>
							<!-- Recipient SSN -->
							<xsd:element name="SSN" type="SSNType">
								<xsd:annotation>
									<xsd:documentation>
										<Description>Recipient SSN</Description>
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<!-- Recipient Name -->
							<xsd:element name="Name" type="PersonNameType">
								<xsd:annotation>
									<xsd:documentation>
										<Description>Recipient name</Description>
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
						<!-- Recipient is an Individual -->
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="BusinessRecipient">
					<xsd:complexType>
						<xsd:sequence>
							<!-- Recipient EIN -->
							<xsd:element name="EIN" type="EINType">
								<xsd:annotation>
									<xsd:documentation>
										<Description>Recipient EIN</Description>
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<!-- Recipient Name -->
							<xsd:element name="Name">
								<xsd:annotation>
									<xsd:documentation>
										<Description>Payer name</Description>
									</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:complexContent>
										<xsd:extension base="BusinessNameType">
											<xsd:attribute name="NameControl" type="BusinessNameControlType" use="required"/>
										</xsd:extension>
									</xsd:complexContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<!-- Recipient is a Business -->
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<!-- Recipient Address -->
			<xsd:choice minOccurs="0">
				<!-- Recipient US Address -->
				<xsd:element name="RecipientUSAddress" type="USAddressType">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Recipient US address</Description>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<!-- Recipient Foreign Address -->
				<xsd:element name="RecipientForeignAddress" type="ForeignAddressType">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Recipient foreign address</Description>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<!-- Account Number -->
			<xsd:element name="AccountNumber" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Account Number</Description>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="StringType">
						<xsd:maxLength value="30"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="TINNot" type="CheckboxType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>2nd TIN not.</Description>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="CUSIPNumber" type="CUSIPNumberType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>CUSIP Number</Description>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="FATCAFilingReqInd" type="CheckboxType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>FATCA Filing Requirement</Description>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ChkBxForm8949" minOccurs="0" maxOccurs="6">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Applicable check box on Form 8949</Description>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="String2Type">
						<xsd:enumeration value="A"/>
						<xsd:enumeration value="B"/>
						<xsd:enumeration value="D"/>
						<xsd:enumeration value="E"/>
						<xsd:enumeration value="X"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="DescOfProp" type="String50Type" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Description of property</Description>
						<LineNumber>1a</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice minOccurs="0">
				<xsd:element name="AcquiredDt" type="DateType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Date Acquired</Description>
							<LineNumber>1b</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="AcquiredTxt" type="String20Type" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Date Acquired - Text description</Description>
							<LineNumber>1b</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:choice minOccurs="0">
				<xsd:element name="SoldDisposedDt" type="DateType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Date sold or disposed</Description>
							<LineNumber>1c</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="SoldDisposeTxt" type="String20Type" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Date sold or disposed - Text Description</Description>
							<LineNumber>1c</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:choice minOccurs="0">
				<xsd:element name="Proceeds" type="USAmountType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Proceeds</Description>
							<LineNumber>1d</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="ProceedsTxt" type="String20Type" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Proceeds - Text Description</Description>
							<LineNumber>1d</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:choice minOccurs="0">
				<xsd:element name="CostBasis" type="IntegerNNType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Cost or other basis</Description>
							<LineNumber>1e</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="CostBasisTxt" type="String20Type" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Cost or other basis - Text Description</Description>
							<LineNumber>1e</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="AccruedMarketDiscount" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Accrued market discount</Description>
						<LineNumber>1f</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="WashSaleLoss" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Wash sale loss disallowed</Description>
						<LineNumber>1g</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="TypeGainLoss" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Type of gain or loss</Description>
						<LineNumber>2</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:choice minOccurs="0">
							<xsd:element name="ShortTerm" type="CheckboxType"/>
							<xsd:element name="LongTerm" type="CheckboxType"/>
						</xsd:choice>
						<xsd:element name="Ordinary" type="CheckboxType" minOccurs="0"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:choice minOccurs="0">
				<xsd:element name="ProceedsCollectibles" type="CheckboxType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Check if proceeds from collectibles</Description>
							<LineNumber>3</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="ProceedsQOF" type="CheckboxType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							<Description>Check if proceeds from a Qualified Opportunity Fund (QOF)</Description>
							<LineNumber>3</LineNumber>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="FedIncTaxWH" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Federal income tax withheld</Description>
						<LineNumber>4</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="NoncoveredSec" type="CheckboxType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Check if noncovered security</Description>
						<LineNumber>5</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ReportedIRS" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Reported to IRS</Description>
						<LineNumber>6</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:choice>
						<xsd:element name="GrossProceeds" type="CheckboxType"/>
						<xsd:element name="NetProceeds" type="CheckboxType"/>
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="LossNotAllowed" type="CheckboxType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Check if loss is not allowed based on amount in 1d</Description>
						<LineNumber>7</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ProfitLossRealized" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Profit or loss realized in current year on closed contracts</Description>
						<LineNumber>8</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="UnrealizedProfitLossPrevYr" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Unrealized profit or loss on open contracts previous year</Description>
						<LineNumber>9</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="UnrealizedProfitLossCurYr" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Unrealized profit or loss on open contracts current year</Description>
						<LineNumber>10</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="AggregateProfitLoss" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Aggregate profit or loss on contracts</Description>
						<LineNumber>11</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="BasisReported" type="CheckboxType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Check if basis reported to IRS</Description>
						<LineNumber>12</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Bartering" type="USAmountType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						<Description>Bartering</Description>
						<LineNumber>13</LineNumber>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="State1099BStateLocalTaxGrp" type="StateLocalTaxGrpType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>
						<Description>State1099B State Local Tax Group</Description>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
